export enum ChannelType {
	POINT_TO_POINT = "POINT_TO_POINT",
	PUBLISH_SUBSCRIBE = "PUBLISH_SUBSCRIBE",
	REQUEST_RESPONSE = "REQUEST_RESPONSE",
	STREAM = "STREAM",
	DEAD_LETTER = "DEAD_LETTER",
	DATATYPE = "DATATYPE",
}
